### ISSUE TITLE
Rewrite 12 .jar file won't open properly

### ISSUE THREAD

**Issue by Zion131313** [DegenDomain/LolilithsThroneIssueTracker#1]
**Details**
Upon attempting to run the .jar file for Rewrite 12, the "data" folder is created, an error is written to the error log, and then nothing further occurs.
Reading the error log and poking around in the source code led me to find that a line (line 399, which I assume was added in this update) in the Properties.java file (game/Properties.java) attempts to fetch a "karma" value from the player, which involves the use of a method from the "Main.game" object before the object is actually defined.

**To Reproduce**
Just run the .jar file from Rewrite 12.

Error log attached for reference.
[error.zip](https://github.com/DegenDomain/LolilithsThroneIssueTracker/files/11669119/error.zip)

**Comment by DrakeFaewylde** [comment]
Should be fixed for next update. Please open a new issue if the issue persists in R13.

Thanks for the report.
