### ISSUE TITLE
Cannot load the precompiled build

### ISSUE THREAD

**Issue by Minxxinthegarden** [DegenDomain/LolilithsThroneIssueTracker#12]
I've recently downloaded the r18.00 build from here. When I extract the build it functions fine, but when I go to run the WIN.jar that comes with it I get sent a "A Java Exception has occurred" error.

Understandably, reproducing it may be hard to impossible on another computer. Would you recommend I do a java reinstall?

![image](https://github.com/DegenDomain/LolilithsThroneIssueTracker/assets/140981030/241192f4-654c-4d60-a886-1e46f9c6b4b4)

**Comment by DrakeFaewylde** [comment]
Do you have multiple versions of Java installed?

This game runs on Java 17.0.4 or higher.

**Comment by Minxxinthegarden** [comment]
I downloaded JDK 20 and it worked. Thanks for the clarification.
I am curious, did you include in the github description that it requires the JDK and not just the JRE? If you haven't then I'd suggest updating the text to include that.
