### ISSUE TITLE
Proposed fix for level gain upon load bug

### ISSUE THREAD

**Issue by Zion131313** [DegenDomain/LolilithsThroneIssueTracker#19]
In GameCharacter.java, in the getLevel() method, change the line "if (Main.game == null || !Main.game.isStarted()) return 1;" to something like "if (Main.game == null || !Main.game.isStarted()) return 10000;".

This will instead cause all characters to be treated as level 10000 during loading, but this basically only matters when checking against the exp needed to level up, and appears to have no further repercussions.

The line in question in the file is 16163, at least in the R18 source.

Alternatively, the getExperienceNeededForNextLevel() method could be changed so that instead of running getLevel() under the conditions that normally cause that line it instead feeds a very large number into itself, or simply returns a very large number.

**Comment by DrakeFaewylde** [comment]
Thanks for the research and hard work.

Will be implemented in next update (current build r18.0.0) unless a better solution comes along before then.
