### ISSUE TITLE
Rewrite 12 Bug compilation post

### ISSUE THREAD

**Issue by Zion131313** [DegenDomain/LolilithsThroneIssueTracker#2]
**Details**
So far some bugs that I have found that leave no error log information (error log remains empty) are:
- Finch does not give the slaver license quest when you enquire about it. The dialogue plays out as normal, but the quest is not granted.
- The transformation menu is usable right from the beginning of the game (with all possible transformation options present), however, any changes made therein are not reflected on the player, despite exiting and re-entering the menu maintaining changes made. (Note: This persists through reloads). Curiously, entering the debug transformation menu and exiting that makes it such that entering the phone transformation menu from that point forth opens the debug transformation menu instead, and this also persists through reloads (reloading from before one did any of that).
- Posters can be put up in Slaver Alley without having the relevant quest, right from the start of the game.

**Comment by DrakeFaewylde** [comment]
Fixed these for the next update.

Thanks for the report. :3
