### ISSUE TITLE
Rewrite 12 Bug Compilation 2

### ISSUE THREAD

**Issue by Zion131313** [DegenDomain/LolilithsThroneIssueTracker#3]
**Details**
- "Meet Enforcer" button is available in the shopping arcade without relevant quest
- Attempting to access the vending machine in submission breaks the ui (phantom buttons (clickable, invisible, with correct tooltip buttons), text on the screen doesn't change)
- Upon achieving a victory against an encounter in the bat caverns, pressing the "Remove character" button (only tested that one, Idk about the others) freezes the ui (phantom buttons, no text change, minimap remains unclickable (game thinks one is still in combat). You can still go phone -> map and fast travel back one tile (if one tile is all it took to get an encounter), but then there's the fact that movement if you don't get an encounter is not reflected on the minimap, meaning that put simply, existing in the bat caverns is impossible. Note: Pressing where the "explore" button should be in the borked ui properly forces a new encounter, which plays out as it should, but no matter how it ends (I tried giving them money), the result is just going back to the borked ui state, now with the tail end of the new encounter on screen instead of the previous one.
- Demons everywhere spawn chance appears to be broken, as after turning it on, leaving the chance as it was, I got nothing but demons spawning in the regular dominion alleyways.
- Wolf pack spawns in alleyways have no dialogue, throwing an error.

Attached is today's full log, from me just trying to play the game how I felt like playing it and running into all these bugs. Can't tell which bugs threw which errors, wasn't paying enough attention sorry, except "Error loading challenge data from save file", which was written every time I loaded a save. Don't think it'll be much help, but including it anyway, since it's not empty.

[error.log](https://github.com/DegenDomain/LolilithsThroneIssueTracker/files/11711274/error.log)

(Note: Not a completely clean installation, using 1 race mod and 1 "status" mod which reports daily earnings and costs, from my testing they do not affect these results. A singular line has been removed from the beginning of the error log to do with the race mod for clarity.)

**Comment by DrakeFaewylde** [comment]
- Meet Enforcer bug fixed.
- Vending Machine bug (should be) fixed.
- Bat Caverns - I was unable to reproduce this bug, and have no idea what's causing it. The error log didn't help in this regard. There were some changes made while fixing these other bugs that may have affected this, so I'll mark this as closed along with the others.
- demonsEverywhere was implemented in a rush, and should be working as intended with R12 Hotfix 3. (Math.random() returns a float between 0 and 1; demonsEverywhereChance was set up as 0 or 5+... you see the issue lol)
- Wolf pack dialogue was simply non-existent. Must have been nuked at some point when rolling things back after major errors a while back. There's some simple placeholder-ish text in for now. There may be other missing text, please report if you find any.

Thanks for the reports, and R12 Hotfix 3 has been released addressing the issues.
