### ISSUE TITLE
Rewrite 12 Companion loading problem

### ISSUE THREAD

**Issue by virtuemaster** [DegenDomain/LolilithsThroneIssueTracker#4]
Saving while a slave companion is in your party makes the save unloadable. I also could not remove them from my party while playing in said saves.

[error.log](https://github.com/DegenDomain/LolilithsThroneIssueTracker/files/11713960/error.log)

**Comment by DrakeFaewylde** [comment]
Fixed. Hotfix 4 released. Thanks for the report.
