### ISSUE TITLE
GUI Issue in Bat Caves

### ISSUE THREAD

**Issue by PvtJohnson** [DegenDomain/LolilithsThroneIssueTracker#8]
**Describe the bug**
On a normal bat cave tile, there are 'ghost' buttons.  On River or Cave tiles, the ghost buttons are not there.

**To Reproduce**
Enter the Bat Caves and move around the various tiles.

**Expected behavior**
You normally expect only the Explore button to appear while moving and exploring tiles in the caves.

**Screenshots**
![bat caves](https://github.com/DegenDomain/LolilithsThroneIssueTracker/assets/137666094/d69ef97f-7066-4e37-b0dd-57db80c54efd)

**Desktop (please complete the following information):**
           Game Version : 0.4.8.5_87 - REWRITE V14            
         Java : 17.0.2 [64-bit] (Oracle Corporation)          
                   OS : Windows 10 (amd64)                    
      Mod folders present: innoxia, lolification_project      
                      End Of Information

**Comment by DrakeFaewylde** [comment]
Should be fixed in the next update/hotfix. If not, let us know here.

Thanks for the report.
